### ISSUE TITLE
Create builds for earlier OS X (e.g. Mavericks)

### ISSUE THREAD

**Issue by nihilus** [stonesam92/ChitChat#107]
Builds fine on Mavericks aka 10.9 for me, cannot see a reason to set deployment target to 10.10.

**Comment by andersio** [comment]
ChitChat uses WKWebView, which is officially said to be available on 10.10 or later.

**Comment by nihilus** [comment]
Yeah I figured it out... So there are two options if I rewire the program: 1) Don't use WKWebView and use whether programs like Tinder++ use. 2) Try to check the source code for WKWebKit (if available) and ship it as a private framework.
