### ISSUE TITLE
The group/contact info covers msg area

### ISSUE THREAD

**Issue by i5o** [stonesam92/ChitChat#11]
Hey, Just trying the app.

I noticed the info of contact/group cover the msg area.

I mean:
In whatsmac:
-> Info closed
![captura de pantalla 2015-06-15 a la s 1 17 31](https://cloud.githubusercontent.com/assets/2650479/8153031/6b890038-12fc-11e5-83c9-ace3eb8dd67a.png)
-> Info open
![captura de pantalla 2015-06-15 a la s 1 17 23](https://cloud.githubusercontent.com/assets/2650479/8153030/6b8802aa-12fc-11e5-9e7f-e4eed34850f2.png)

Whatsapp web:
-> Info closed
![captura de pantalla 2015-06-15 a la s 1 18 04](https://cloud.githubusercontent.com/assets/2650479/8153032/6b89f240-12fc-11e5-92be-2cbfd7806e90.png)
-> Info opened
![captura de pantalla 2015-06-15 a la s 1 18 06](https://cloud.githubusercontent.com/assets/2650479/8153033/6b8dc9f6-12fc-11e5-93f6-2c4d58a31423.png)

I think it should work like WhatsApp web does

Good job anyway with the app
Greetings,
i5o

**Comment by stonesam92** [comment]
Yeah, this needs fixing. 

It's a side effect of hacking the page's CSS such that when the app is fullscreen, the content expands to fill the whole window rather than having that green/grey backing that you see in those browser screenshots.

**Comment by orenonou** [comment]
@stonesam92 
This issue can be solved by removing lines 24 and 25 from inject.js:
div.pane.pane-chat { width : 100%; } \
div.pane.pane-intro { width : 100%; } \

This also solves the width problem with the recent conversations list on the left side (The width size was too small in comparison with the original web view).

Here's some before and after screenshot :)

![captura-de-pantalla-2015-08-19-a-las-23 58 04](https://cloud.githubusercontent.com/assets/3266017/9374816/f6577166-46cf-11e5-935c-3721182113b8.jpg)

Tested on the latest version of El Capitan beta 7

**Comment by stonesam92** [comment]
Fixed in #35 by @0x6368, and available in the 1.3 release of ChitChat.
