### ISSUE TITLE
Quick reply from notifications

### ISSUE THREAD

**Issue by theld07** [stonesam92/ChitChat#114]
Would be possible to add the quick reply feature to the project? I tried to do that, the Xcode part was fine, i got stuck with the JS script. I was able to write a string into the (horrible) contenteditable div used by WhatsApp Web as the message input box but WA Web seems to enable the "send" button only when a keyboard input is received, so I'm not able to automatically send the string! Whats wrong with WhatsApp Web?

**Comment by crystalminds** [comment]
Yes it's possible. We did it too with Messages for WhatsApp (http://apple.co/1O8dt4M). Just look further into the HTML5 contenteditable part it does not work the same as an input element since it can also include HTML.
