### ISSUE TITLE
Mute the App

### ISSUE THREAD

**Issue by HansWurst90** [stonesam92/ChitChat#120]
Is there a way to mute the whole app?
I want to recieve the notifications, but without sound.

**Comment by theld07** [comment]
I think that you're talking about the WhatsApp Web notification tone. That sound, can be muted by clicking on the settings button (the three dots) on the top of your chat list, then click on Notifications and from there you can disable the sound. Hope this helps! :)

— L. 

Inviato da iPhone

**Comment by HansWurst90** [comment]
Thanks a lot! That was exactly what i was looking for.
