### ISSUE TITLE
Avoid being "online" when window is minimized

### ISSUE THREAD

**Issue by turizoft** [stonesam92/ChitChat#13]
I think this should be the default behaviour. When window is minimised or unfocussed user shouldn't appear as "online". See Telegram for Mac.

**Comment by stonesam92** [comment]
Do you know what the behaviour of web.whatsapp.com in the browser is regarding this?

**Comment by 0x6368** [comment]
When the window looses focus  (minimized or when another window has focus), you have to wait for a couple of seconds and will not be online any more. This already works for me on ChitChat.

**Comment by stonesam92** [comment]
ChitChat seems to work fine in this regard for me too. 

I have noticed that tweaks which enabled WhatsApp Web on iOS cause some issues in this area, but since WhatsApp Web is now fully supported in the stock app, they are no longer necessary.
