### ISSUE TITLE
sidebar issue with resized window  

### ISSUE THREAD

**Issue by kintaro1981** [stonesam92/ChitChat#139]
Example in the attached GIF
![chitchat-issue](https://cloud.githubusercontent.com/assets/2357176/14343958/bd6bd870-fca4-11e5-95b0-1217b8f799f4.gif)

**Comment by antonbkn** [comment]
Hey man, check out the active development here: https://github.com/Neo11/ChitChat. I believe this problem is already solved.

**Comment by kintaro1981** [comment]
oh! thank you.
I was using the stonesam92 version.

thank you
