### ISSUE TITLE
Adding up/down arrow keyboard shortcuts to support traversal of conversations.

### ISSUE THREAD

**Issue by yangshun** [stonesam92/ChitChat#14]
Hey Sam, I have been using WhatsMac/ChitChat for a while now and am liking it a lot. Would like to ask whether you are open to the idea of supporting up/down arrow keyboard shortcuts to support traversal of conversations (when input field is empty)? Facebook messenger, Telegram and WeChat support this behaviour. 

If you are open to adding it, I'll gladly make a pull request to add these keyboard shortcuts :smile:

**Comment by stonesam92** [comment]
Sounds like a good idea, if you could add that functionality I'd definitely be willing to accept it!

**Comment by yangshun** [comment]
Closed by #15
