### ISSUE TITLE
No emoticons on latest version

### ISSUE THREAD

**Issue by wynstep** [stonesam92/ChitChat#20]
Hello, I am the only person without emoticons on latest version of chitchat?
Can someone help me?
![screen shot 2015-07-10 at 12 48 56](https://cloud.githubusercontent.com/assets/7643476/8617220/0d39d8bc-2702-11e5-8f6c-6ac650428be2.png)

**Comment by GavinThePacMan** [comment]
+1! Might try take a look myself. Might be something small like a class change!

**Comment by stonesam92** [comment]
Have you upgraded to 1.2? Should be fixed now.

Its not been pushed out over autoupdate because the updater framework doesn't handle app renaming well and WhatsMac is now called ChitChat

**Comment by stonesam92** [comment]
You can download the update manually here https://github.com/stonesam92/ChitChat/releases

**Comment by GavinThePacMan** [comment]
I have not! My apologies, I should have checked for a newer version first. Many thanks! Working perfectly! :D

**Comment by wynstep** [comment]
Thank you!!!
Now is fixed :)

**Comment by stonesam92** [comment]
No worries; looking to find a solution to the auto-update issue today so hopefully no one else will experience this!
