### ISSUE TITLE
Menu item doesn't show up fully

### ISSUE THREAD

**Issue by adisutanto** [stonesam92/ChitChat#21]
![chitchat](https://cloud.githubusercontent.com/assets/2127973/8632366/b8e4f954-27c9-11e5-83b7-f152bbfd9fa6.png)
On clicking menu (three dots) button on the top left side, I'm seeing "New group" only but not other options. (Note: I've masked my chats)

My OS X version: Yosemite 10.10.4

**Comment by yangshun** [comment]
Strange, this is what I'm seeing instead: 
<img width="193" alt="screen shot 2015-07-21 at 4 33 08 pm" src="https://cloud.githubusercontent.com/assets/1315101/8796289/3b4a9f26-2fc6-11e5-823d-de1dbf23af49.png">

Try on the web browser, what do you see? Might be just WhatsApp doing some A/B testing.

**Comment by adisutanto** [comment]
It's not A/B testing. The behavior in my Mac has always been like that.

Tried on Safari Version 8.0.7 (10600.7.12), and apparently it has the same issue with the incomplete menu: 
![screen shot 2015-07-22 at 23 14 30](https://cloud.githubusercontent.com/assets/2127973/8829205/f100d914-30c7-11e5-9960-8bd8160197dd.png)

So this is not a ChitChat issue.

**Comment by yangshun** [comment]
<img width="206" alt="screen shot 2015-07-23 at 12 28 24 am" src="https://cloud.githubusercontent.com/assets/1315101/8830952/c8db2386-30d1-11e5-8545-c62fc9516a1c.png">

This is what I see on my Safari Version 8.0.6 (10600.6.3). That's really weird.

But I guess if it's not a ChitChat issue then it's not really relevant?

**Comment by adisutanto** [comment]
You're right. It's irrelevant, thus I'm closing the issue.
