### ISSUE TITLE
After take the qrcode picture, the screen don't load

### ISSUE THREAD

**Issue by TiagoGouvea** [stonesam92/ChitChat#28]
Some times it stay with a little green circle on the middle of screen, some times it just don't show anything, the form still blank..

**Comment by tschoffelen** [comment]
Seems to me as if this bug is part of Whatsapp web itself, happened to me as well in Safari. Usually it works the second time, after a reload.

**Comment by stonesam92** [comment]
I think that @TiagoGouvea is correct; this is a WhatsApp Web bug and unrelated to ChitChat.
