### ISSUE TITLE
Whatsapp Web available for iOS now!

### ISSUE THREAD

**Issue by MarcelDEV** [stonesam92/ChitChat#30]
Please Update your Information - Whatsapp Web ist now available for iOS Devices

**Comment by nasht00** [comment]
And it seems to work so far with ChitChat

**Comment by MarcelDEV** [comment]
it works! perfect!

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Can confirm, its working with iOS without Jailbreak ... TOP

**Comment by stonesam92** [comment]
Fixed in #29 by @casdr. Thanks everyone for bringing this to my attention!
