### ISSUE TITLE
Can't drag on 10.11

### ISSUE THREAD

**Issue by RvMouche** [stonesam92/ChitChat#32]
Hey,

First kuddo's for the app, have been using it since I got whatsapp web for iOS :). However on el cap I can't drag the window. Only changing it's size works as a workaround. If you could look into that it would be nice. (Y)

**Comment by PebaVermelho** [comment]
+1 for this request.

**Comment by bjornpost** [comment]
+1

**Comment by ericprieto** [comment]
+1

**Comment by pixada** [comment]
+1

**Comment by mlegenhausen** [comment]
+1

**Comment by cesards** [comment]
+1

**Comment by Saudumm** [comment]
As long as the windows is in the background, you can drag it near the top border.

**Comment by iamDecode** [comment]
+1. Dragging near the top border does not work for me.

**Comment by Saudumm** [comment]
The windows has to be inactive. Works for me on PB5

**Comment by iamDecode** [comment]
+2, works for me. Weird bug though :p Thanks!

**Comment by brandoseven** [comment]
+1 bug is confirmed here, too

**Comment by stonesam92** [comment]
I don't have a device running 10.11 to test on, so there's not much I can do to fix this until it is released publicly.

I am assuming that this is a bug in 10.11 rather than ChitChat, since no deprecated or private APIs are used to manage the window.

That said, if anybody can provide a PR which fixes this I'd be happy to merge it and would appreciate it.

**Comment by kintaro1981** [comment]
On 10.11 I can drag only if the chitchat window is inactive.
I have this issue only on Chitchat.

**Comment by Zakay** [comment]
+1 Dragging the app is such a pain. Dragging near the top border is not a solution.

**Comment by brandoseven** [comment]
The bug is still present in Beta 8.

**Comment by nickschot** [comment]
And in the GM, dragging does work when the window is not in focus.

**Comment by PebaVermelho** [comment]
The bug is still present for me on GM.

**Comment by laszlomenyhart** [comment]
+1

**Comment by laszlomenyhart** [comment]
hi @stonesam92 !

I think fb-mac-messenger app creators faced with the same issue, and they solved it, this topics might be useful for you as well:
https://github.com/rsms/fb-mac-messenger/issues/156

Hope this helps!

**Comment by stonesam92** [comment]
Finally fixed in versions 1.4 and later.
