### ISSUE TITLE
No profile picture at notifications

### ISSUE THREAD

**Issue by blaichch** [stonesam92/ChitChat#4]
When getting a message there is no profile picture in the notification. Instead it only shows a white file icon.
![screen shot 2015-05-27 at 12 07 49](https://cloud.githubusercontent.com/assets/12624897/7833711/316f8aee-0469-11e5-9495-42126252f935.png)

**Comment by stonesam92** [comment]
That's strange, I get the WhatsMac icon.

I'm busy over the next two days with exams, but will look into this afterwards.

If I remember correctly, accessing actual profile pictures in the native half of the app is more difficult than you'd imagine; you have to be authenticated to download them from the server but there's no easy way to access a `WKWebView`'s authenticated session from Objective-C. 

If I can't figure a way around that though, I will at least ensure that you get the WhatsMac icon and not that white file icon.
