### ISSUE TITLE
Browser upgrade warning

### ISSUE THREAD

**Issue by gmarcus** [stonesam92/ChitChat#40]
Running ChitChat v1.2 (1.2.0)

It is complaining that it needs Safari 7+.

I am running OS X Yosemite 10.10.4 with Safari 8.0.7
Chrome [Version 44.0.2403.130 (64-bit)] is my default desktop browser.

![screenshot 2015-08-20 18 44 37](https://cloud.githubusercontent.com/assets/111017/9397529/923765a0-476b-11e5-8c52-45351deb46e8.png)

**Comment by albertolive** [comment]
Me too...

**Comment by panoriega** [comment]
//Whatsapp web only works with specific user agents
    //_webView._customUserAgent = @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A";


    _webView._customUserAgent = @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/8.0.8 Safari/7046A194A";
Date: Thu, 20 Aug 2015 16:15:28 -0700

**Comment by bgottsch** [comment]
It's a problem with the user agent. What solved my problem was to change line 82 of the AppDelegate.m file from

```_webView._customUserAgent = @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A";``` 

to

```_webView._customUserAgent = @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.1.50 (KHTML, like Gecko) Version/9.0 Safari/601.1.50";```

Then you simple compile the app again. Hope it helps.

(Thanks for the app!)

**Comment by Fulviuus** [comment]
I have submitted a pull request with a fix, but yes, all you have to do is update the user agent:
https://github.com/stonesam92/ChitChat/pull/41

**Comment by jin** [comment]
Same issue, @bgottsch's fix works.

**Comment by xopiwoxo** [comment]
Sorry can anyone help me, where to find the AppDelegate.m? :)

**Comment by mkozjak** [comment]
@xopiwoxo:
./WhatsMac/AppDelegate.m

@bgottsch: +1: works like a charm :)

**Comment by maccouch** [comment]
@xopiwoxo it's in the source code. Open Xcode, add this github address to " a new project from a scm repository", change the line in AppDelegate.m and just hit CMD+B to build the corrected app. Else, just wait a couple of hours till the developer fixes the issue and issue a new precompiled binary that you can download..

**Comment by mofman** [comment]
Anyone able to zip up their recompile and post?

**Comment by navgarcha** [comment]
Sure, here you go: https://s3.amazonaws.com/uploads.hipchat.com/7809/170737/mvnW4KyDbf3MYYU/ChitChat-hotfixed.zip

**Comment by phikes** [comment]
Hm, I am unable to expand that archive. :(

**Comment by fightbulc** [comment]
second that

**Comment by mofman** [comment]
third

**Comment by navgarcha** [comment]
Hrmm, odd - updated with new link that should work: https://s3.amazonaws.com/uploads.hipchat.com/7809/170737/k6PsgbkD1QqXKjP/ChitChat.app.zip

**Comment by phikes** [comment]
Works, thank you so much! :)

**Comment by fightbulc** [comment]
No I am getting the following notification when I am trying to start the app:

```“ChitChat.app” is damaged and can’t be opened. You should move it to the Trash.```

**Comment by mofman** [comment]
Works for me thanks!

**Comment by endyasr** [comment]
I've the same issue
“ChitChat.app” is damaged and can’t be opened. You should move it to the Trash.

**Comment by DiederikvandenB** [comment]
Same issue as @fightbulc & @endyasr.

**Comment by wrow** [comment]
On the "is damaged and can’t be opened" error ... just try 

    chmod +x ChitChat.app/Contents/MacOS/ChitChat

in your applications directory.

**Comment by albertolive** [comment]
Works!

**Comment by fightbulc** [comment]
No luck. Still the same error. Running Yosemite if that matters.

**Comment by renatoagds** [comment]
Works for me! OS X 10.10.5.. Thanks guys! =)

**Comment by wrow** [comment]
@fightbulc 
Just try it again ... i can't tell you why, but i had to download the .zip again, removed the .app directory and started over. For everybody in doubt: the md5 sum of the .zip working for me is 9280f2c18edb9d1b4442314cd98e7d7d.

**Comment by fenomeno0chris** [comment]
Sorry for the dumb question, but how does it work?

"On the "is damaged and can’t be opened" error ... just try

chmod +x ChitChat.app/Contents/MacOS/ChitChat
in your applications directory."

**Comment by wrow** [comment]
@fenomeno0chris 
**Long:** https://en.wikipedia.org/wiki/File_system_permissions
**Short:** All files have attributes. One of them is if you can execute them. If you open the ChitChat.app osx application, in fact you open ChitChat.app/Contents/MacOS/ChitChat ... its kind of a shortcut. `chmod +x` markes the file as executable.

**Comment by BjornB2** [comment]
“ChitChat.app” is damaged and can’t be opened. You should move it to the Trash.

Did chmod +x ChitChat.app/Contents/MacOS/ChitChat

El Capitan 10.11 bèta (15A262e)

Just FYI. I can wait for El Capitan compatible release of course.

**Comment by endyasr** [comment]
no working also with chmod. Yosemite 10.10.5

**Comment by fightbulc** [comment]
@wrow the issue concerns if you allow apps to run which are not from the app store or from identified developers. Settings > Security > Allow apps downloaded from...

**Comment by th-ch** [comment]
If chmod is not working, try
~~~~
 xattr -rc ChitChat.app 
~~~
It should work fine (works for me on Yosemite 10.10.5)

**Comment by endyasr** [comment]
It works!!
 xattr -rc ChitChat.app

**Comment by HenriqueKraemer** [comment]
Worked here with @navgarcha build! (Yosemite 10.10.5)

**Comment by adrinavarro** [comment]
Working fine now. It has a pop-up message asking for a different browser for full media capabilities, but that's OK.

**Comment by stonesam92** [comment]
Fixed in bab30cb7cc82cd1cf68ca6d73170ca41d80fd534 by @Fulviuus and released in ChitChat 1.3.

Thanks everybody for reporting the issue and bringing it to my attention!

**Comment by AlexKokoro** [comment]
Hello and Merry Christmas!
I have noticed that when i connect through the QR code, ChitChat says i should use chrome or firefox to use all the feature of whatsapp, so i think ChitChat is automatically using Safari to connect to WhatsappWeb.

How can I change the ChitChat default browser from Safari to Chrome? (Chrome is already my default browser in OS X El Capitan)

Thank you for your time and work.

**Comment by adrinavarro** [comment]
You can't. It's a WebView element, which uses the native OS engine that's
essentially Safari. Just ignore the warnings and it will work with most
features.

On Sat, Dec 26, 2015 at 12:09 PM, AlexKokoro <notifications@github.com> wrote:
Hello and Merry Christmas!
I have noticed that when i connect through the QR code, ChitChat says i should
use chrome or firefox to use all the feature of whatsapp, so i think ChitChat is
automatically using Safari to connect to WhatsappWeb.

How can I change the ChitChat default browser from Safari to Chrome? (Chrome is
already my default browser in OS X El Capitan)

Thank you for your time and work.

—
Reply to this email directly or view it on GitHub
[https://github.com/stonesam92/ChitChat/issues/40#issuecomment-167317262] .[https://github.com/notifications/beacon/AADKat32X_-JqQKhwTqnu1ff1xTMVAYhks5pTmzmgaJpZM4FvhVm.gif]

**Comment by sieren** [comment]
I guess it can easily be fixed by modifying https://github.com/stonesam92/ChitChat/blob/master/WhatsMac/AppDelegate.m#L101 to version 9.0?

This project could need some more maintainers though, seems like nothing has been updated/merged for a while :(

**Comment by AlexKokoro** [comment]
Thank you guys
