### ISSUE TITLE
Incompatibility in OS X El Capitan Beta 7

### ISSUE THREAD

**Issue by avatsaev** [stonesam92/ChitChat#44]
In the latest beta OS X, the app shows this message: 

"WhatsApp Web works with Safari 7+" : 

<img width="843" alt="screen shot 2015-08-21 at 4 31 53 am" src="https://cloud.githubusercontent.com/assets/518974/9400106/96053e62-47bd-11e5-90c2-013b9411beb2.png">

**Comment by avatsaev** [comment]
updated with this pull request https://github.com/stonesam92/ChitChat/pull/45/

**Comment by mkozjak** [comment]
A possible fix is on #40

**Comment by stonesam92** [comment]
Fixed in release 1.3 of ChitChat.

This issue was unrelated to the OS version but rather was caused when WhatsApp updated WhatsApp Web shortly after adding support for iOS devices.
