### ISSUE TITLE
Apparent compatibility problem with safari

### ISSUE THREAD

**Issue by jjvelascog** [stonesam92/ChitChat#47]
Hi, i'd been using Chit Chat last months with no problem, and yesterday started to fail in the way explained below. Which may be the problem?
Thanks in advance
<img width="1280" alt="captura de pantalla 2015-08-21 a las 11 30 26" src="https://cloud.githubusercontent.com/assets/7219690/9410820/c7d5ae78-47f8-11e5-930a-2f710c7c5a59.png">

**Comment by renatoagds** [comment]
Hi @jjvelascog, you can found a temporary solution in #40 ... Is a problem in user agent.

**Comment by jjvelascog** [comment]
Thanks, i downloaded the @navgarcha solutions. Works like a charm!

**Comment by Ckdeveloper** [comment]
this is resolution: 

 _webView._customUserAgent = @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0.8 Safari/7046A194A";

Please  developer project...  input this code in source code and fix this.
