### ISSUE TITLE
Failed to download a picture in a conversation

### ISSUE THREAD

**Issue by osh123** [stonesam92/ChitChat#5]
In a conversation with a group or a single person, try to download a picture I received leads to an error:
![screen shot 2015-05-27 at 14 04 01](https://cloud.githubusercontent.com/assets/1708736/7834593/5deaa206-0479-11e5-8572-5ea3116db633.png)

**Comment by stonesam92** [comment]
Yeah I can reproduce this. 

This was working fine about a week ago though, so something seems to have changed in WhatsApp Web. 

I'm busy with exams over the next two days but will fix this afterwards.

**Comment by blaichch** [comment]
Alternatively you can just drag & drop the picture out of the chatwindow until it's fixed.

**Comment by osh123** [comment]
Thanks!

**Comment by stonesam92** [comment]
Thanks @blaichch! Didn't realise that worked. 

As of 82136900ab924e9bac5d857e01597e1644c39eba, an alert is shown to the user advising them to drag-and-drop the file into finder to save it, and the error page is not shown.

This will be included in the 1.1 release in the next day or so.
