### ISSUE TITLE
Show an icon for ChitChat in the status menu bar

### ISSUE THREAD

**Issue by adrinavarro** [stonesam92/ChitChat#50]
It would be nice to have an opt-in icon that opens ChitChat in the status bar (top right hand of the screen), much like most other apps do, for quick access (ie. Telegram).

**Comment by stonesam92** [comment]
Agreed. This should be added pretty soon, see #22.

**Comment by adrinavarro** [comment]
I'm reopening to thank you for the icon! And also mention that's it's not entirely fitting other icons in size… hmm.

![screen shot 2015-10-01 at 15 30 11](https://cloud.githubusercontent.com/assets/51818/10221888/5df56308-6851-11e5-94db-25a9e60071d9.png)

I suck at design — but would a pull request with a cropped icon help with this?

**Comment by gfpacheco** [comment]
Would be nice to have an option to disable the icon, since some people (me included) don't want it there.

**Comment by stonesam92** [comment]
@gfpacheco: you can, in versions 1.4.1 and newer. You can toggle the status bar on and off with a toggle in the menu bar: ChitChat -> Hide Status Icon

**Comment by stonesam92** [comment]
@adrinavarro yeah, that PR would help! :)

**Comment by adrinavarro** [comment]
Any way to obtain editable files for the icons? Would look better than just scaling them /cc @congbach
