### ISSUE TITLE
Visual improvements

### ISSUE THREAD

**Issue by DotTheI** [stonesam92/ChitChat#52]
It would be nice to have the original WhatApp icons used in the application (here they are https://www.dropbox.com/s/jm2h6xd2c8fj6sf/AppIcon.icns?dl=0), the fonts in chats and the users list to become smaller as the application window is changed and the users list to show user icons only when the windows is the smallest/narrowest

**Comment by dariobanfi** [comment]
I agree for the icon, but I think they don't use it for legal problems right? You can just use your custom icon though... I use this high res version: http://imgur.com/0QaiTxD

**Comment by stonesam92** [comment]
As I've discussed on similar issues/pull requests, WhatsApp have not licensed their copyrighted images to ChitChat. 

Feel free to manually replace the images in your own personal installation, but it is extremely unlikely that they can ever be distributed as part of ChitChat.

**Comment by DotTheI** [comment]
@stonesam92 Alright, I forgot about the copyright issue. That's understandable. Manually replacing the icon is what I do.

Still, it would be good to see smaller fonts :)

And thank you very much for developing this application!!
