### ISSUE TITLE
Error: "Timed out to start connect"

### ISSUE THREAD

**Issue by saada** [stonesam92/ChitChat#53]
![screen shot 2015-08-26 at 11 14 46 am](https://cloud.githubusercontent.com/assets/1087987/9502039/b5f7b91e-4be3-11e5-85d7-d45f71caf251.png)

**Comment by saada** [comment]
Is anyone else experiencing this?

**Comment by steilerDev** [comment]
same here

**Comment by sebask** [comment]
Got the same error. Seems to be an outage on WhatsApp's side as @steilerDev noted.

**Comment by RvMouche** [comment]
Yea, Whatsapp Web has had some issues in the last few hours. By the way, Chitchat was using extreme levels of power here while it couldn't connect until I shut it off. Maybe worth investigating. (forgot to save the logs..)

**Comment by steilerDev** [comment]
After trying to reconnect, the application consumed 90% of CPU until I killed it. 

@RvMouche How do you save logs in ChitChat, in case I can reproduce the problem.

**Comment by saada** [comment]
it's workin' again for me... it's on their end so... closing! thanks everyone
