### ISSUE TITLE
Change User Agent?

### ISSUE THREAD

**Issue by Jianlucah** [stonesam92/ChitChat#56]
Hi, is it possible to change User Agent? I ask this 'cause at the open i see this windows.

![schermata 2015-08-30 alle 23 07 42](https://cloud.githubusercontent.com/assets/14016475/9569457/5effcc96-4f6c-11e5-9d7d-ec16a040a5d2.png)

Translate: To use all the functions of WhatsApp Web as take a photo and record a voice message, we recommend using Google Chrome, Mozilla Firefox or Opera

**Comment by stonesam92** [comment]
ChitChat formerly used Chrome's user agent string, but things broke when WhatsApp Web started doing per-browser things that would didn't work when the page expected to be running on Chrome but was actually running in `WKWebView`.

Other user agents might work right now, but going forward Safari is probably the best choice, in case WhatsApp Web contains further browser-specific code at some point in the future.
