### ISSUE TITLE
ChitChat for OS X 10.7?

### ISSUE THREAD

**Issue by Giogi89** [stonesam92/ChitChat#64]
How about a ChitChat version for Mac OS X Lion? Thanks in advantage :)

**Comment by markimarc** [comment]
Lion is a bit outdated, i don't think it's relevant.

**Comment by Giogi89** [comment]
http://www.intego.com/mac-security-blog/os-x-market-share-statistics-1-in-5-macs-still-unsupported/http://www.intego.com/mac-security-blog/os-x-market-share-statistics-1-in-5-macs-still-unsupported/

**Comment by stonesam92** [comment]
Unfortunately this is just not possible without a full rewrite, since ChitChat makes use of `WKWebView`, only available from 10.10 onwards.
