### ISSUE TITLE
Distribute via Homebrew/Cask?

### ISSUE THREAD

**Issue by esttorhe** [stonesam92/ChitChat#71]
Not an issue per sé but more like a question. 
Would there be an interest in supporting `Cask`/`Homebrew` distribution?

I would love to help if there was interest in this since I would definitely use it.

Thanks

**Comment by m4grio** [comment]
+1

**Comment by esttorhe** [comment]
Today I had some time to play with this and after running this:
```console
brew cask create chitchat
```

I was greeted with the following message:
>Error: A Cask for ChitChat already exists. Run "brew cask cat ChitChat" to see it.

So I ran:
```console
brew cask search ChitChat
```
>==> Exact match
>chitchat

Which means `ChitChat` already supports distribution via `Cask`.

Closing this issue; thanks though :)
