### ISSUE TITLE
Can't disable status bar icon

### ISSUE THREAD

**Issue by macuduranti** [stonesam92/ChitChat#76]
I couldn't find an option to disable the status bar icon added in last update (1.4.0). If there isn't, having the option to disable it would be great.

**Comment by DotTheI** [comment]
I also would like to disable the menu bar icon

**Comment by laszlomenyhart** [comment]
Same here. It has no function.

**Comment by thomasbachem** [comment]
The menu bar icon is superfluous and clutters my menu bar. Please add a way to disable it.

**Comment by zerbfra** [comment]
Yep - I would like to disable it too

**Comment by roffel** [comment]
Would indeed be nice to have an option to toggle the icon in the menu bar. But thanks for this great app and the window drag fix.

Keep up the good work!

**Comment by genghizkhan91** [comment]
It would be nice to be able to disable the menu bar icon if it continues to have no purpose. Also, if you continue to keep it, then it might be a good idea to have a version for the dark menu bar, currently, it only has an icon for the light menu bar (which looks horrible on the dark menu bar).

**Comment by mvberkum** [comment]
Would also be great to have Chitchat either in the dock, or in the menubar. Now its in both. So having an option to hide chitchat in the dock would be nice.
