### ISSUE TITLE
Chit Chat Top Bar Icon Barely Visible in Dark Mode

### ISSUE THREAD

**Issue by roni-estein** [stonesam92/ChitChat#80]
<img width="404" alt="screen shot 2015-10-01 at 10 41 19 am" src="https://cloud.githubusercontent.com/assets/8517475/10225557/fc96b850-6828-11e5-80bf-9eabd50e91a7.png">

If you are working in "Dark Mode", available from Yosemite onwards, the top icon is just a dark gray blur.

**Comment by l0ngestever** [comment]
+1. And fix it to a monochrome icon please.

**Comment by stonesam92** [comment]
Fixed in 1.5.1
