### ISSUE TITLE
Hide menu bar icon

### ISSUE THREAD

**Issue by milosmilikic** [stonesam92/ChitChat#86]
Since menu bar icon is added, I would like to have possibility to hide it. 

Cheers!

**Comment by gonch** [comment]
+1

**Comment by cristianobecker** [comment]
+1

**Comment by joselitojunior** [comment]
+1

**Comment by andersio** [comment]
You can now toggle it on and off via "ChitChat > Show/Hide Status Icon" in v1.4.1.
https://github.com/stonesam92/ChitChat/releases/tag/1.4.1

**Comment by milosmilikic** [comment]
Awesome!
