### ISSUE TITLE
Cannot attach pictures.

### ISSUE THREAD

**Issue by ahmad19** [stonesam92/ChitChat#9]
![screen shot 2015-05-30 at 1 16 59 am](https://cloud.githubusercontent.com/assets/2041827/7891389/eb9e278e-0669-11e5-914d-e063150f3a12.png)

Steps to reproduce: 
1. click on the attach icon
2. as the icon pops up.. try clicking it.. it doesnt open up the browse file window

OS: Yosemiti 10.10.3 (14D136)

**Comment by stonesam92** [comment]
See #7. 

`WKWebView` doesn't work properly with file upload `input` tags, but you can drag and drop images from Finder into the WhatsMac window to send them.

A temporary 'fix' which explains this to the user when they click the button has been added, but not yet distributed as a release/update. 

I will release it as an update in the next day or so.

**Comment by ahmad19** [comment]
Yes the drag n drop works.
