### ISSUE TITLE
View Message Info

### ISSUE THREAD

**Issue by altern8tif** [stonesam92/ChitChat#96]
Just wondering if it's possible to replicate the Message Info like in the iOS/Android versions?

![image](https://cloud.githubusercontent.com/assets/5793364/10454167/560b4110-71e5-11e5-9ddb-bf873413d32e.png)

**Comment by doersino** [comment]
Since this app is just a wrapper around WhatsApp web, this will only be possible once WhatsApp Web supports this. That said, this feature is at the top of my wishlist, too.

**Comment by altern8tif** [comment]
:+1: Thanks!

**Comment by altern8tif** [comment]
Dev on this repo seems to have stopped.  Will close issue.
