### ISSUE TITLE
Add option to mute notification sound

### ISSUE THREAD

**Issue by toxxmeister** [stonesam92/ChitChat#99]
It'd be nice to have an option to mute the notification sound.

**Comment by doersino** [comment]
See #51.

**Comment by mordi34** [comment]
Select Notifications from this menu and choose to not have sound: 
![screen shot 2016-03-29 at 12 35 42 am](https://cloud.githubusercontent.com/assets/4019660/14092304/31ff0984-f546-11e5-9cc8-96c0f5d61c48.png)
